name: ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms:  ${{ steps.qemu.outputs.platforms }}
          push: true
          tags: |
            ${{ github.repository }}:${{ github.sha }}

      - name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: docker.io/${{ github.repository }}:${{ github.sha }}
          dst: |
            ghcr.io/${{ steps.qemu.outputs.platforms }}:${{ github.sha }}

      - name: Tag latest
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: docker.io/${{ github.repository }}:${{ github.sha }}
          dst: |
            docker.io/${{ github.repository }}:latest
            ghcr.io/${{ steps.qemu.outputs.platforms }}:latest